version: '3.8'

services:
  next:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    env_file:
      - .env
      - .env.local
    networks:
      - internal_network
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - internal_network

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal_network

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mongo-data:
  postgres-data:
  mysql-data:

networks:
  internal_network:
    driver: bridge
