version: '3.8'

services:
  cs-express:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: 
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  mongo-data:
  postgres-data:
  mysql-data:
