apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-controller
  namespace: default
spec:
  defaultBackend:
    service:
      name: cs-express-service # Name of a default service to route traffic to
      port:
        number: 80 # Port number of the default service
