apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-ingress-controller
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: mongodb
      port: 27017
      targetPort: 27017
    - name: mysql
      port: 3306
      targetPort: 3306
